# Generated by Django 5.1.7 on 2025-09-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_userprofile_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='disaster_severity',
            new_name='disasterSeverity',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='disaster_type',
            new_name='disasterType',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='image_url',
            new_name='imageUrl',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='incident_location',
            new_name='incidentLocation',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='reporter_location',
            new_name='reporterLocation',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.AddField(
            model_name='report',
            name='reporterEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reporterId',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='reporterName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reporterPhone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
