# Generated by Django 5.1.7 on 2025-09-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_rename_disaster_severity_report_disasterseverity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
